#!/bin/bash
#PBS -N NAME
#PBS -j oe
#PBS -l nodes=2:ppn=16

# Unload any OpenMPI
module unload openmpi

# NAMD
export NAMD_PATH=/share/apps/NAMD_2.11_Linux-x86_64-ib-smp-cuda
export LD_LIBRARY_PATH=$NAMD_PATH:$LD_LIBRARY_PATH
export NAMD=$NAMD_PATH/namd2
export CHARMRUN=$NAMD_PATH/charmrun

cd $PBS_O_WORKDIR

rm -f nodelist
touch nodelist
nodes=$( cat $PBS_NODEFILE | awk '!seen[$0]++')
for node in $nodes; do
   echo $node >> nodelist
done
NP=`cat $PBS_NODEFILE | wc -l`
NN=`cat $PBS_NODEFILE | awk '!seen[$0]++' | wc -l`
NP_1=$(expr $NP - $NN)
NP_2=$(($NP-$NN*2))

echo "#!/bin/csh" > mpiexec_wrapper
echo "exec mpiexec -machinefile ./nodelist -mca btl openib,self,sm \$*" >> mpiexec_wrapper
chmod +x mpiexec_wrapper

date
