#!/bin/bash

PDB="$1"
[ $# -eq 0 ] && { echo "mkvmd> Usage: $0 [PSF/PDB]"; exit 1; }

if [ ! -f $PDB ]; then
    echo -e "$PDB \nStructure not found!"
    exit 0
fi

cat > tcl <<EOF
mol new $PDB waitfor all
foreach ii {RBD PROA HETA HETB} cc {A B C D} {
    set sel [atomselect top "segname \$ii"]
    \$sel set chain \$cc
}
set sel [atomselect top "resname HSD HSE HSP"]; \$sel set resname HIS
set sel [atomselect top "resname ILE and name CD"]; \$sel set name CD1
set sel [atomselect top "not hydrogen and segname RBD PROA HETA HETB"]
\$sel writepdb fixed.pdb
quit
EOF
vmd -dispdev text -e tcl

rm -f tcl 
