#!/bin/bash

line=`tail -n 1 $1`
echo $line
cat > cell_size.str << EOF
cellBasisVector1 `echo $line | awk '{print $2}'` 0 0
cellBasisVector2 0 `echo $line | awk '{print $6}'` 0
cellBasisVector3 0 0 `echo $line | awk '{print $10}'`
cellOrigin `echo $line | awk '{print $14" "$15" "$16}'`
EOF
