#!/bin/zsh
source ~/.zshrc

PDB=$1
TRJ=$2
[ $# -eq 0 ] && { echo "mkvmd> Usage: $0 [PSF/PDB]"; exit 1; }

if [ ! -f $PDB ]; then
    echo -e "$PDB \nStructure not found!"
    exit 0
fi

if [ ! -f $TRJ ]; then
    echo -e "$TRJ \nTrajectory not found!"
    exit 0
fi

cat > tcl <<EOF
mol new $PDB first 0 last -1 step 1 filebonds 1 autobonds 1 waitfor all
mol addfile $TRJ first 0 last -1 step 1 filebonds 1 autobonds 1 waitfor all
mol delrep 0 top
mol representation Licorice 0.300000 12.000000 12.000000
mol color Name
mol selection {noh segname PROC}
mol material Goodsell
mol addrep top
mol selupdate 0 top 0
mol colupdate 0 top 0
mol scaleminmax top 0 0.000000 0.000000
mol smoothrep top 0 0
mol drawframes top 0 {now}
mol clipplane center 0 0 top {0.0 0.0 0.0}
mol clipplane color  0 0 top {0.5 0.5 0.5 }
mol clipplane normal 0 0 top {0.0 0.0 1.0}
mol clipplane status 0 0 top {0}
mol clipplane center 1 0 top {0.0 0.0 0.0}
mol clipplane color  1 0 top {0.5 0.5 0.5 }
mol clipplane normal 1 0 top {0.0 0.0 1.0}
mol clipplane status 1 0 top {0}
mol clipplane center 2 0 top {0.0 0.0 0.0}
mol clipplane color  2 0 top {0.5 0.5 0.5 }
mol clipplane normal 2 0 top {0.0 0.0 1.0}
mol clipplane status 2 0 top {0}
mol clipplane center 3 0 top {0.0 0.0 0.0}
mol clipplane color  3 0 top {0.5 0.5 0.5 }
mol clipplane normal 3 0 top {0.0 0.0 1.0}
mol clipplane status 3 0 top {0}
mol clipplane center 4 0 top {0.0 0.0 0.0}
mol clipplane color  4 0 top {0.5 0.5 0.5 }
mol clipplane normal 4 0 top {0.0 0.0 1.0}
mol clipplane status 4 0 top {0}
mol clipplane center 5 0 top {0.0 0.0 0.0}
mol clipplane color  5 0 top {0.5 0.5 0.5 }
mol clipplane normal 5 0 top {0.0 0.0 1.0}
mol clipplane status 5 0 top {0}
mol representation NewCartoon 0.300000 10.000000 4.100000 0
mol color SegName
mol selection {protein}
mol material AOChalky
mol addrep top
mol selupdate 1 top 0
mol colupdate 1 top 0
mol scaleminmax top 1 0.000000 0.000000
mol smoothrep top 1 0
mol drawframes top 1 {now}
mol clipplane center 0 1 top {0.0 0.0 0.0}
mol clipplane color  0 1 top {0.5 0.5 0.5 }
mol clipplane normal 0 1 top {0.0 0.0 1.0}
mol clipplane status 0 1 top {0}
mol clipplane center 1 1 top {0.0 0.0 0.0}
mol clipplane color  1 1 top {0.5 0.5 0.5 }
mol clipplane normal 1 1 top {0.0 0.0 1.0}
mol clipplane status 1 1 top {0}
mol clipplane center 2 1 top {0.0 0.0 0.0}
mol clipplane color  2 1 top {0.5 0.5 0.5 }
mol clipplane normal 2 1 top {0.0 0.0 1.0}
mol clipplane status 2 1 top {0}
mol clipplane center 3 1 top {0.0 0.0 0.0}
mol clipplane color  3 1 top {0.5 0.5 0.5 }
mol clipplane normal 3 1 top {0.0 0.0 1.0}
mol clipplane status 3 1 top {0}
mol clipplane center 4 1 top {0.0 0.0 0.0}
mol clipplane color  4 1 top {0.5 0.5 0.5 }
mol clipplane normal 4 1 top {0.0 0.0 1.0}
mol clipplane status 4 1 top {0}
mol clipplane center 5 1 top {0.0 0.0 0.0}
mol clipplane color  5 1 top {0.5 0.5 0.5 }
mol clipplane normal 5 1 top {0.0 0.0 1.0}
mol clipplane status 5 1 top {0}
mol rename top ionized.psf
set viewpoints([molinfo top]) {{{1 0 0 -2.4201} {0 1 0 5.50334} {0 0 1 23.6773} {0 0 0 1}} {{0.846449 -0.295871 0.442667 0} {0.14999 -0.665208 -0.731417 0} {0.510873 0.685509 -0.518691 0} {0 0 0 1}} {{0.0628555 0 0 0} {0 0.0628555 0 0} {0 0 0.0628555 0} {0 0 0 1}} {{1 0 0 0} {0 1 0 0} {0 0 1 0} {0 0 0 1}}}
lappend viewplist [molinfo top]
set topmol [molinfo top]
# done with molecule 0
foreach v \$viewplist {
  molinfo \$v set {center_matrix rotate_matrix scale_matrix global_matrix} \$viewpoints(\$v)
}
unset viewplist
mol top \$topmol
unset topmol
EOF

vmd -e tcl
