#!/bin/bash
source ~/.zshrc
conda activate pmx
export GMXLIB=/opt/anaconda3/envs/pmx/lib/python2.7/site-packages/pmx-2.0+41.g7725833-py2.7-macosx-10.7-x86_64.egg/pmx/data/mutff45

rm -r chains
mkdir chains

cat > tcl <<'EOF'
mol new md.pdb
set sel [atomselect top "resname HSD HSE HSP"]; $sel set resname HIS
set sel [atomselect top "resname ILE and name CD"]; $sel set name CD1
set sel [atomselect top "name OT1"]; $sel set name O
set sel [atomselect top "name OT2"]; $sel set name OXT
foreach ii {A B} {
    set sel [atomselect top "noh segname PRO$ii"]
    $sel set chain $ii
    $sel writepdb chains/$ii.pdb
}
mol new peptide_mutate.pdb
set sel [atomselect top "resname HSD HSE HSP"]; $sel set resname HIS
set sel [atomselect top "resname ILE and name CD"]; $sel set name CD1
set sel [atomselect top "name OT1"]; $sel set name O
set sel [atomselect top "name OT2"]; $sel set name OXT
set sel [atomselect top "all"]
$sel set chain X
$sel writepdb chains/X.pdb
quit
EOF
vmd -dispdev text -e tcl
rm tcl

rm mol.pdb
for ii in A B X; do
    grep "^ATOM" chains/$ii.pdb >> mol.pdb
done

gmx pdb2gmx -f mol.pdb

cp topol_Protein_chain_X.itp topol_Protein_chain_X.itp.BAK
cp posre_Protein_chain_X.itp posre_Protein_chain_X.itp.BAK

pmx gentop -itp topol_Protein_chain_X.itp -o topol_Protein_chain_X.itp -ff charmm22starmut.ff 

echo "\n;Include Position restraint file" >> topol_Protein_chain_X.itp
sed '1,/Include Position restraint file/D' topol_Protein_chain_X.itp.BAK >> topol_Protein_chain_X.itp

rm \#*
