#!/bin/bash

[ $# -ne 3 ] && { echo -e "!!!Caution: Execute in directory containing t1, t2, t3...\nUsage: $0 <zju??> <port> <remote pwd>"; exit 1; }

rsync -rptD --progress -e "ssh -p$2" $1:$3/ . --include="*/" \
                                            --include="*/t*.restart.coor" \
                                            --include="*/t*.restart.vel" \
                                            --include="*/t*.restart.xsc" \
                                            --include="*/t*.log" \
                                            --include="*/t*.namd" \
                                            --include="[0-9]" \
                                            --exclude="*"
