#!/bin/bash
#PBS -N NAME
#PBS -j oe
#PBS -l nodes=12:ppn=16

export MPI_PATH=/usr/mpi/gcc/openmpi-1.8.5
export PATH=$MPI_PATH/bin:$PATH
export LD_LIBRARY_PATH=$MPI_PATH/lib64:$LD_LIBRARY_PATH
MPIRUN=$MPI_PATH/bin/mpirun
MPIEXEC=$MPI_PATH/bin/mpiexec

nodefile=/tmp/$PBS_JOBID.nodelist
echo group main ++cpus 16 ++shell ssh > $nodefile
nodes=$( cat $PBS_NODEFILE | awk '!seen[$0]++')
for node in $nodes; do
   echo host $node >> $nodefile
done
NP=`cat $PBS_NODEFILE | wc -l`
NN=`cat $PBS_NODEFILE | awk '!seen[$0]++' | wc -l`
NP2=$(expr $NP - $NN)

cd $PBS_O_WORKDIR
date
$CHARMRUN +p${NP2} ++nodelist $nodefile $NAMD cuda.namd ++verbose > cuda_ibverbs_smp_6.log
