#!/bin/bash
#PBS -N us-zPOSaa-NUM
#PBS -j oe
#PBS -l nodes=1:ppn=16

export NAMD_PATH=/home/kevin/opt/NAMD_2.10_Linux-x86_64-multicore-CUDA
export LD_LIBRARY_PATH=$NAMD_PATH:$LD_LIBRARY_PATH
export NAMD=$NAMD_PATH/namd2
export CHARMRUN=$NAMD_PATH/charmrun

export CUDA_HOME=/share/apps/cuda
export LD_LIBRARY_PATH=$CUDA_HOME/lib:$LD_LIBRARY_PATH

nodefile=/tmp/$PBS_JOBID.nodelist
echo group main ++cpus 16 ++shell ssh > $nodefile
nodes=$( cat $PBS_NODEFILE | awk '!seen[$0]++')
for node in $nodes; do
   echo host $node >> $nodefile
done
NP=`cat $PBS_NODEFILE | wc -l`
NN=`cat $PBS_NODEFILE | awk '!seen[$0]++' | wc -l`
NP2=$(expr $NP - $NN)

cd $PBS_O_WORKDIR
date
$NAMD +p8 +idlepoll us-zPOSaa-NUM.namd > us-zPOSaa-NUM.log
wait
date
