#!/bin/bash
#PBS -A bip126
#PBS -N us-NN
#PBS -j oe
#PBS -l walltime=12:00:00
#PBS -l nodes=672
#PBS -M mcfc1301@gmail.com
#PBS -m ae
##
#
#./opt/modules/3.2.6.7/init/bash
source $MODULESHOME/init/bash
#module swap PrgEnv-pgi PrgEnv-gnu
#module load craype-hugepages8M
#module load fftw
#module swap PrgEnv-cray PrgEnv-gnu
#module load rca
#module load cudatoolkit

module swap PrgEnv-pgi PrgEnv-gnu
#module swap PrgEnv-cray PrgEnv-gnu
module load rca
module load craype-hugepages8M
export HUGETLB_DEFAULT_PAGE_SIZE=8M
export HUGETLB_MORECORE=no

module load namd

export MPICH_PTL_SEND_CREDITS=-1
export MPICH_MAX_SHORT_MSG_SIZE=8000
export MPICH_PTL_UNEX_EVENTS=80000
export MPICH_UNEX_BUFFER_SIZE=100M

cd /lustre/atlas1/bip126/proj-shared/BAR-PH/us-asym/run
date
aprun -n 24 -r 1 -N 1 -d 15 namd2 +ppn 15 +pemap 1-15 +commap 0 us-z616-NN.namd  > us-z616-NN.log &
aprun -n 24 -r 1 -N 1 -d 15 namd2 +ppn 15 +pemap 1-15 +commap 0 us-z630-NN.namd  > us-z630-NN.log &
aprun -n 24 -r 1 -N 1 -d 15 namd2 +ppn 15 +pemap 1-15 +commap 0 us-z640-NN.namd  > us-z640-NN.log &
aprun -n 24 -r 1 -N 1 -d 15 namd2 +ppn 15 +pemap 1-15 +commap 0 us-z650-NN.namd  > us-z650-NN.log &
aprun -n 24 -r 1 -N 1 -d 15 namd2 +ppn 15 +pemap 1-15 +commap 0 us-z660-NN.namd  > us-z660-NN.log &
aprun -n 24 -r 1 -N 1 -d 15 namd2 +ppn 15 +pemap 1-15 +commap 0 us-z670-NN.namd  > us-z670-NN.log &
aprun -n 24 -r 1 -N 1 -d 15 namd2 +ppn 15 +pemap 1-15 +commap 0 us-z680-MM.namd  > us-z680-MM.log &
aprun -n 24 -r 1 -N 1 -d 15 namd2 +ppn 15 +pemap 1-15 +commap 0 us-z695-MM.namd  > us-z695-MM.log &
aprun -n 24 -r 1 -N 1 -d 15 namd2 +ppn 15 +pemap 1-15 +commap 0 us-z710-MM.namd  > us-z710-MM.log &
aprun -n 24 -r 1 -N 1 -d 15 namd2 +ppn 15 +pemap 1-15 +commap 0 us-z725-MM.namd  > us-z725-MM.log &
aprun -n 24 -r 1 -N 1 -d 15 namd2 +ppn 15 +pemap 1-15 +commap 0 us-z740-MM.namd  > us-z740-MM.log &
aprun -n 24 -r 1 -N 1 -d 15 namd2 +ppn 15 +pemap 1-15 +commap 0 us-z755-MM.namd  > us-z755-MM.log &
aprun -n 24 -r 1 -N 1 -d 15 namd2 +ppn 15 +pemap 1-15 +commap 0 us-z765-MM.namd  > us-z765-MM.log &
aprun -n 24 -r 1 -N 1 -d 15 namd2 +ppn 15 +pemap 1-15 +commap 0 us-z770-MM.namd  > us-z770-MM.log &
aprun -n 24 -r 1 -N 1 -d 15 namd2 +ppn 15 +pemap 1-15 +commap 0 us-z785-MM.namd  > us-z785-MM.log &
aprun -n 24 -r 1 -N 1 -d 15 namd2 +ppn 15 +pemap 1-15 +commap 0 us-z800-OO.namd  > us-z800-OO.log &
aprun -n 24 -r 1 -N 1 -d 15 namd2 +ppn 15 +pemap 1-15 +commap 0 us-z815-OO.namd  > us-z815-OO.log &
aprun -n 24 -r 1 -N 1 -d 15 namd2 +ppn 15 +pemap 1-15 +commap 0 us-z830-OO.namd  > us-z830-OO.log &
aprun -n 24 -r 1 -N 1 -d 15 namd2 +ppn 15 +pemap 1-15 +commap 0 us-z845-OO.namd  > us-z845-OO.log &
aprun -n 24 -r 1 -N 1 -d 15 namd2 +ppn 15 +pemap 1-15 +commap 0 us-z860-OO.namd  > us-z860-OO.log &
aprun -n 24 -r 1 -N 1 -d 15 namd2 +ppn 15 +pemap 1-15 +commap 0 us-z875-OO.namd  > us-z875-OO.log &
aprun -n 24 -r 1 -N 1 -d 15 namd2 +ppn 15 +pemap 1-15 +commap 0 us-z890-OO.namd  > us-z890-OO.log &
aprun -n 24 -r 1 -N 1 -d 15 namd2 +ppn 15 +pemap 1-15 +commap 0 us-z905-OO.namd  > us-z905-OO.log &
aprun -n 24 -r 1 -N 1 -d 15 namd2 +ppn 15 +pemap 1-15 +commap 0 us-z920-OO.namd  > us-z920-OO.log &
aprun -n 24 -r 1 -N 1 -d 15 namd2 +ppn 15 +pemap 1-15 +commap 0 us-z935-OO.namd  > us-z935-OO.log &
aprun -n 24 -r 1 -N 1 -d 15 namd2 +ppn 15 +pemap 1-15 +commap 0 us-z950-OO.namd  > us-z950-OO.log &
aprun -n 24 -r 1 -N 1 -d 15 namd2 +ppn 15 +pemap 1-15 +commap 0 us-z965-OO.namd  > us-z965-OO.log &
aprun -n 24 -r 1 -N 1 -d 15 namd2 +ppn 15 +pemap 1-15 +commap 0 us-z980-OO.namd  > us-z980-OO.log &

wait
