#!/bin/bash

[ $# -eq 0 ] && { echo -e "Usage: $0 [-run|-lrun] [gpu ID] [prefix: only with -lrun]"; exit 1; }

if [[ "$1" == "-run" ]]; then

    sed -e "s/gmx mdrun -v/gmx mdrun -ntmpi 1 -ntomp 16 -gpu_id $2 -nb gpu -pme gpu -bonded gpu -v/g" \
        -e "s/^gmx_d mdrun -v -deffnm \${mini_prefix}/gmx mdrun -ntmpi 1 -ntomp 16 -v -deffnm \${mini_prefix}/g" \
        -e "s/^set cntmax = 10/set cntmax = 1/g" \
        README > wrapper
    csh wrapper

elif [[ "$1" == "-lrun" ]]; then

    trr_is_needed=false
    if $trr_is_needed; then
    sed -e "s/^nsteps.*/nsteps                  = 500000/g" \
        -e "s/^nstvout.*/nstvout                 = 50000/g" \
        -e "s/^nstfout.*/nstfout                 = 50000/g" \
        -e "s/^nstxout.*/nstxout                 = 50000/g" \
        -e "s/^nstxout.*/nstxout-compressed      = 50000/g" \
        step7_production.mdp > step7_production_trr.mdp
    gmx_mpi grompp -o md-trr.tpr -f step7_production_trr.mdp -c step7_1.gro -t step7_1.cpt -n index.ndx -p topol.top
    fi

    [ ! -f md.tpr ] && gmx_mpi grompp -o md.tpr -f step7_production.mdp -c step7_1.gro -t step7_1.cpt -n index.ndx -p topol.top

    MDRUN_GPU="gmx mdrun -ntmpi 1 -ntomp 16 -gpu_id $2 -pme gpu -nb gpu -bonded gpu -update gpu"
    #$MDRUN_GPU -v -deffnm step7_1
    
    #prefix=t1
    if [ ! -f ${prefix}.cpt ]; then
      $MDRUN_GPU -v -s md.tpr -deffnm ${prefix} -nsteps -1
    else
      $MDRUN_GPU -v -s md.tpr -cpi ${prefix}.cpt -deffnm ${prefix} -nsteps -1
    fi

fi
