#PBS -N M1-t2
#PBS -q md
#PBS -l nodes=1:ppn=1:gpus=1
##PBS -l walltime=99:00:00
#PBS -S /bin/bash
#PBS -j oe

date
echo "CUDA_VISIBLE_DEVICES: $CUDA_VISIBLE_DEVICES"
export LD_LIBRARY_PATH=/public/software/lib/:$LD_LIBRARY_PATH
source /public/software/compiler/intel/intel-compiler-2017.5.239/bin/compilervars.sh intel64
cd $PBS_O_WORKDIR
echo $PBS_O_WORKDIR

NAMD="/public/software/apps/NAMD_3.0alpha9/namd3"

$NAMD +p1 +devices 0 t2.part2.namd >& log/t2.part2.log
