#!/bin/bash -l
#SBATCH -A m3165
#SBATCH -S 4
#SBATCH -N 32
#SBATCH -p knl -C knl,quad,flat
#SBATCH -t 12:00:00

module load gromacs
srun -n 512 mdrun_mpi_sp -s Run_NPT300K.tpr -deffnm Run_NPT300K -cpi Run_NPT300K.cpt -noappend  -ntomp 4 -dlb yes -pin off >& test.log
