#PBS -A PAA0030
#PBS -N SPcluster1_0_ligprep
#PBS -j oe
#PBS -m ae
#PBS -M cool.28@osu.edu
#PBS -l walltime=4:00:00
#PBS -l nodes=1:ppn=1
#PBS -S /bin/sh
qstat -f $PBS_JOBID
module load schrodinger
cd $PBS_O_WORKDIR
pbsdcp -p '*' $TMPDIR
cd $TMPDIR
host=`cat $PBS_NODEFILE|head -1`
nproc=`cat $PBS_NODEFILE|wc -l`
$SCHRODINGER/ligprep -WAIT -HOST ${host}:${nproc} -isd SP_input_cluster1_0.sdf -omae ligprep_cluster1_0-out.maegz -bff 14 -i 2 -ph 7.4 -pht 0.0 -ac -s 5 -r 1
ls -l
pbsdcp -p '*' $PBS_O_WORKDIR