#! /bin/bash

RECP=/users/PAS1326/osu9603/cpf1/vina/receptor/complex/c1_model1.pdbqt
CONF=/users/PAS1326/osu9603/cpf1/vina/config_complex_f10000.txt
OUTPUT=/users/PAS1326/osu9603/cpf1/vina/ligand/nat_product/res_complex

for f in *.pdbqt; do
    b=`basename $f .pdbqt`
    echo Processing ligand $b
    mkdir -p $OUTPUT/$b
    ~/opt/autodock_vina_1_1_2_linux_x86/bin/vina --config $CONF --receptor $RECP --ligand $f --out $OUTPUT/$b/out.pdbqt --log $OUTPUT/$b/log.txt
done
