#!/bin/bash

[ $# -eq 0 ] && { echo -e "Usage: mkgmx_trjconv [Output Prefix] [PDB] [Index File] [Trajectory] [tpr] [cpt]"; exit 1; }

stripped=false
pick_frame=false

OUTPUT=$1
PDB=$2
IDX=$3
TRJ=$4
TPR=$5

echo 0 | gmx trjconv -f ${TRJ} -s ${TPR} -n ${IDX} -pbc nojump -o unwrap.xtc 
gmx trjconv -f unwrap.xtc -s ${TPR} -n ${IDX} -fit rot+trans -o out-${OUTPUT}.xtc -dt 1000

if $stripped; then
  gmx editconf -f ${PDB} -n ${IDX} -o stripped.pdb
  gmx convert-tpr -s ${TPR} -n ${IDX} -o stripped.tpr
fi

if $pick_frame; then
  CPT=$6
  echo 0 | gmx trjconv -f ${CPT} -s ${TPR} -n ${IDX} -pbc nojump -o picked.restart.pdb
fi

rm -f \#* unwrap.xtc
