#!/bin/bash
#SBATCH --job-name=NAME
#SBATCH --partition=gpu3090
#SBATCH --qos=8gpus
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=6
#SBATCH --gpus=1

module load gromacs/2023.2-gcc-9.5.0-jzxesel
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

# Equilibration

bash mkgmx_run.sh 0
ln -s output/md.tpr .


# Production

MDRUN="gmx_mpi mdrun -gpu_id 0 -nb gpu -pme gpu -bonded gpu -update gpu"

prefix=t1
if [ ! -f ${prefix}.cpt ]; then
  $MDRUN_GPU -v -s md.tpr -deffnm ${prefix} -nsteps -1 -maxh 167
else
  $MDRUN_GPU -v -s md.tpr -cpi ${prefix}.cpt -deffnm ${prefix} -nsteps -1 -maxh 167
fi
