#!/bin/bash
#SBATCH --job-name=NAME
#SBATCH --partition=gpu3090
#SBATCH --qos=8gpus
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=6
#SBATCH --gpus=1

module load gromacs/2023.2-gcc-9.5.0-jzxesel

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

bash wrapper_charmmgui -run 0 
wait

bash wrapper_charmmgui -lrun 0 t1
wait
