#!/bin/bash

# Check if there are no arguments provided
if [ $# -eq 0 ]; then
    echo -e "Usage: trjconv [prefix]"
    exit 1
fi

# Set variables
PREFIX="$1"
TPR_FILE="md.tpr"
INDEX_FILE="index.ndx"
OUTPUT_XTC="${PREFIX}.rewrapped.pf1000ps.xtc"
OUTPUT_XVG="${PREFIX}.rmsd.xvg"
GMX="gmx_mpi"

# Create an index file with molecule groups
#echo -e "group 0\nmol 1\nmol 2\n" | $GMX select -s "$TPR_FILE" -on "$INDEX_FILE"
echo -e "0\n" | $GMX editconf -f "$TPR_FILE" -n "$INDEX_FILE" -o md.pdb

# Process the trajectory by adjusting PBC, centering it and saving every 1000th frame
echo -e "1\n0\n" | $GMX trjconv -s "$TPR_FILE" -f "${PREFIX}.xtc" -n "$INDEX_FILE" -pbc mol -center -ur compact -dt 1000 -o "step1-$OUTPUT_XTC"
echo -e "1\n0\n" | $GMX trjconv -s "$TPR_FILE" -f "step1-$OUTPUT_XTC" -n "$INDEX_FILE" -fit rot+trans -o "$OUTPUT_XTC"

# Calculate RMSD for the trajectory
echo -e "1\n2\n" | $GMX rms -s "$TPR_FILE" -f "${OUTPUT_XTC}" -n "$INDEX_FILE" -o "$OUTPUT_XVG"

# echo 0 | gmx trjconv -s md.tpr -f output/${prefix}.xtc -pbc nojump -dt 1000 -o tmp-nojump-${prefix}.xtc
# echo -e "a 5293 \n q" | gmx make_ndx -n pdb2gmx/index.ndx

rm step[0-9]-$OUTPUT_XTC
