#!/bin/bash
#########################################
## Description: 
##              This runs after solvateNgo.
## Authors: 
##         Kevin C. Chan (work@skblnw.com) 2022.10.25
## Usage: sh 
#########################################

conda activate pymbar

for sim in complex free; do
  mkdir -p xvg
  cd xvg
  for ii in $(seq 0 23); do
    ln -s ../dir$ii/md.xvg dhdl.$ii.xvg
  done
  cd ..
  alchemical_analysis -d xvg -u kcal -g -w -s 1000
done

b=`grep "TOTAL:" complex/xvg/results.txt | awk '{print $17}'`
f=`grep "TOTAL:" free/xvg/results.txt | awk '{print $17}'`
bd=`grep "TOTAL:" complex/xvg/results.txt | awk '{print $19}'`
fd=`grep "TOTAL:" free/xvg/results.txt | awk '{print $19}'`
res=`echo "$b - $f" | bc`
err=`echo "sqrt($bd*$bd+$fd*$fd)" | bc`
echo "$res +- $err"
