#!/bin/bash

LAMBDA=0
mkdir Lambda_$LAMBDA

dir_mdp=MDP_20
MDP=../$dir_mdp/md$LAMBDA.mdp
echo ".mdp files are stored in $MDP"

dir_pdb=pdb2gmx
TOP=../$dir_pdb/topol.top

dir_last=standard
LAST=../$dir_last/output/step5_md.gro

NEXT=md$LAMBDA-1

##############
# Production #
##############

cd Lambda_$LAMBDA

echo "Starting production MD simulation..."

gmx grompp -f $MDP -c $LAST -p $TOP -o $NEXT.tpr

gmx mdrun -ntomp 1 -deffnm $NEXT

echo "Production MD complete. Job completed for lambda = $LAMBDA"