#! /bin/bash

RECP=/users/PAS1326/osu9603/cpf1/vina/receptor/apo/cNN_model1.pdbqt
CONF=/users/PAS1326/osu9603/cpf1/vina/config_apo.txt
OUTPUT=/users/PAS1326/osu9603/cpf1/vina/ligand/nat_product_refined/pdbqt_sort5000/res_apo_cNN

for f in *.pdbqt; do
    b=`basename $f .pdbqt`
    echo Processing ligand $b
    mkdir -p $OUTPUT/$b
    ~/opt/autodock_vina_1_1_2_linux_x86/bin/vina --config $CONF --receptor $RECP --ligand $f --out $OUTPUT/$b/out.pdbqt --log $OUTPUT/$b/log.txt
done
