#!/bin/bash

if [ -z ${1+x} ]; then
  prefixlist="bound free"
else
  prefixlist=$1
fi
echo -e "> Prefixlist is <$prefixlist>"

for prefix in $prefixlist; do
  for trial in `find $prefix -maxdepth 1 -name 'trial[0-9]*' | sort -V`; do
    echo -n "[$trial] "
    switch=`grep TIMING $trial/LOG_fep | tail -n 1 | awk '{print $11}'`
    re='^[0]$'
    if [[ $switch =~ $re ]]; then
      grep "Running FEP window" $trial/LOG_fep | tail -n 1 | awk '{print "Finished "$5"FEP Windows:"}' | tr -d '\n'
      grep TIMING $trial/LOG_fep | tail -n 1 | awk '{printf(" %.0f ns/days, ", $9)}' | tr -d '\n'
      tail -n 1 $trial/alchemy.fepout | awk '{print $19}' | tr -d '\n'
      echo " kcal/mol"
      if [ -e "$trial/fepout" ]; then
        completion_check=`tail -n 1 $trial/fepout | awk '{print $2}'`
        if [ "$completion_check" -ne "1" ]; then
          echo "> Error: Result file for $trial is incomplete."
          grep "^#Free energy change" $trial/alchemy.fepout | awk '{print NR" "$9" "$12" "$19}' > $trial/fepout
        fi
        continue
      else
        grep "^#Free energy change" $trial/alchemy.fepout | awk '{print NR" "$9" "$12" "$19}' > $trial/fepout
      fi
    else
      grep "Running FEP window" $trial/LOG_fep | tail -n 1 | awk '{print "Running FEP Window "$5}' | tr -d '\n'
      grep TIMING $trial/LOG_fep | tail -n 1 | awk '{print " "$11" "$12" "$13" "$9" "$10}'
    fi
  done
  echo "---"
done
